Podstawy grafiki komputerowej: main.cpp File Reference
main.cpp File Reference
#include "SFML/Graphics/Color.hpp"
#include "animatedSpriteSheet.hpp"
#include "engine.hpp"
#include <iostream>
Namespaces
namespace G
Functions
int main ()
Variables
std::string G::basePath = "resources/"
AnimatedSpriteSheet animation (G::basePath+"animation")
Function Documentation
main()
int main ()
Definition at line 12 of file test3/main.cpp.
           {
  Engine::getInstance().setMaxFps(3).setResolution({1000, 1000}).buildWindow();
  animation.setPosition({300, 300});
  animation.setColor(sf::Color::Cyan);
  Engine::getInstance().add(&animation);
  Engine::getInstance().loop();
}
References Engine::add(), animation, Engine::getInstance(), Engine::loop(), Engine::setMaxFps(), AnimatedObject::setPosition(), and Engine::setResolution().
Variable Documentation
animation
AnimatedSpriteSheet animation(G::basePath+"animation") (G::basePath+"animation")
Referenced by main(), and GamePlayer::update().