Podstawy grafiki komputerowej: Ball Class Reference
Ball Class Reference
#include <ball.hpp>
Public Member Functions
Ball (float radius=10, std::size_t pointCount=30)
void setMovementSpeed (float movementSpeed)
void setMoveVectorBase (Point2d moveVectorOrigin)
virtual void update ()
Updates state of object.
virtual void move (Point2d vector)
Translates object in space.
virtual void setPositon (Point2d pos)
bool isDead () const
virtual void setPosition (Point2d pos)
Object position setter.
virtual Point2d getPosition () const
Object position getter.
Private Member Functions
Point2d getMoveVector ()
Private Attributes
float m_movementSpeed {10}
Point2d m_moveVectorBase {}
float m_timeToLife {15}
bool m_dead {false}
Point2d m_position {}
Position of object on screen.
Detailed Description
Definition at line 10 of file ball.hpp.
Constructor & Destructor Documentation
Ball()
Ball::Ball (float radius = 10, std::size_t pointCount = 30)
Definition at line 9 of file ball.cpp.
    : sf::CircleShape(radius, pointCount) {}
Member Function Documentation
getMoveVector()
Point2d Ball::getMoveVector () private
Definition at line 43 of file ball.cpp.
{ return {m_moveVectorBase * m_movementSpeed}; }
References m_movementSpeed, and m_moveVectorBase.
Referenced by update().
getPosition()
Point2d GameObject::getPosition () const virtual inherited
Object position getter.
Definition at line 7 of file GameObject.cpp.
{ return m_position; }
References GameObject::m_position.
isDead()
bool Ball::isDead () const
Definition at line 30 of file ball.cpp.
{ return m_dead; }
References m_dead.
Referenced by handleBalls().
move()
void Ball::move (Point2d vector) virtual
Translates object in space.
Parameters
vector 2D vector added to current object position.
Reimplemented from GameObject.
Definition at line 20 of file ball.cpp.
{
  GameObject::move(vector);
  sf::CircleShape::move(vector.toVector2f());
}
References GameObject::move(), and Point2d::toVector2f().
Referenced by update().
setMovementSpeed()
void Ball::setMovementSpeed (float movementSpeed)
Definition at line 12 of file ball.cpp.
{
  m_movementSpeed = movementSpeed;
}
References m_movementSpeed.
Referenced by throwBallPlayer().
setMoveVectorBase()
void Ball::setMoveVectorBase (Point2d moveVectorOrigin)
Definition at line 16 of file ball.cpp.
{
  m_moveVectorBase = moveVectorBase;
}
References m_moveVectorBase.
Referenced by throwBall().
setPosition()
void GameObject::setPosition (Point2d pos) virtual inherited
Object position setter.
Parameters
pos Position to be set.
Reimplemented in AnimatedObject.
Definition at line 5 of file GameObject.cpp.
{ m_position = pos; }
References GameObject::m_position.
Referenced by AnimatedObject::setPosition(), and setPositon().
setPositon()
void Ball::setPositon (Point2d pos) virtual
Definition at line 25 of file ball.cpp.
{
  GameObject::setPosition(pos);
  sf::Transformable::setPosition(pos.toVector2f());
}
References GameObject::setPosition(), and Point2d::toVector2f().
Referenced by throwBall().
update()
void Ball::update () virtual
Updates state of object.
Implements UpdateableObject.
Definition at line 32 of file ball.cpp.
                  {
  if (m_timeToLife <= 0) {
    m_dead = true;
    return;
  }
  m_timeToLife -= Engine::getInstance().getLastFrameDuration().asSeconds();
  move(getMoveVector() *
       Engine::getInstance().getLastFrameDuration().asSeconds());
}
References Engine::getInstance(), Engine::getLastFrameDuration(), getMoveVector(), m_dead, m_timeToLife, and move().
Referenced by handleBalls().
Member Data Documentation
m_dead
bool Ball::m_dead {false} private
Definition at line 32 of file ball.hpp.
{false};
Referenced by isDead(), and update().
m_movementSpeed
float Ball::m_movementSpeed {10} private
Definition at line 29 of file ball.hpp.
{10};
Referenced by getMoveVector(), and setMovementSpeed().
m_moveVectorBase
Point2d Ball::m_moveVectorBase {} private
Definition at line 30 of file ball.hpp.
{};
Referenced by getMoveVector(), and setMoveVectorBase().
m_position
Point2d GameObject::m_position {} private inherited
Position of object on screen.
Definition at line 14 of file GameObject.hpp.
{};
Referenced by GameObject::getPosition(), GameObject::move(), and GameObject::setPosition().
m_timeToLife
float Ball::m_timeToLife {15} private
Definition at line 31 of file ball.hpp.
{15};
Referenced by update().
The documentation for this class was generated from the following files:
ball.hpp
ball.cpp