Podstawy grafiki komputerowej: FidgetSpinner Class Reference
FidgetSpinner Class Reference
#include <fidgetSpinner.hpp>
Public Types
using animationData_t = std::vector< AnimationFrameData >
Public Member Functions
FidgetSpinner (std::string_view path)
virtual void animate () override
Animates object.
Point2d getCenterPoint () const
void addRotationSpeed (float speed)
void setRotationResistance (float speed)
virtual void setPosition (Point2d pos)
Object position setter.
virtual void move (Point2d vec)
Translates object in space.
virtual Point2d getPosition () const
Object position getter.
Protected Member Functions
int getCurrentAnimationFrameCount () const
sf::IntRect getCurrentAnimationFrameRect () const
float getCurrentAnimationFrameDuration () const
const AnimationFrameData & getCurrentAnimationFrameData () const
void nextFrame ()
void setFrame (const AnimationFrameData &frameData)
void loadFrame (std::istream &stream, animationData_t &animationData)
load frame data from stream
void loadSpritesheet (std::istream &stream, std::string_view configFileDirectoryPath)
void loadFromConfigFile (std::string_view pathToDir)
Private Attributes
float m_rotationResistance {0.1}
float m_rotationspeed {0}
float m_angle {}
std::vector< animationData_t > m_animationsData
int m_currentAnimationTypeIndex
int m_currentFrameId {}
float m_animationTimer {}
Point2d m_position {}
Position of object on screen.
Detailed Description
Definition at line 8 of file fidgetSpinner.hpp.
Member Typedef Documentation
animationData_t
using AnimatedSpriteSheet::animationData_t = std::vector<AnimationFrameData> inherited
Definition at line 24 of file animatedSpriteSheet.hpp.
Constructor & Destructor Documentation
FidgetSpinner()
FidgetSpinner::FidgetSpinner (std::string_view path)
Definition at line 8 of file fidgetSpinner.cpp.
    : AnimatedSpriteSheet(path) {
  LOGINFON;
  Point2d offset(getSize().x / 2.f + 0.5f, getSize().y / 2.f + 0.5f);
  setOrigin(offset.toVector2f());
};
References LOGINFON, and Point2d::toVector2f().
Member Function Documentation
addRotationSpeed()
void FidgetSpinner::addRotationSpeed (float speed)
Definition at line 35 of file fidgetSpinner.cpp.
{ m_rotationspeed += speed; }
References m_rotationspeed.
Referenced by spinTheFidget().
animate()
void FidgetSpinner::animate () override virtual
Animates object.
Reimplemented from AnimatedSpriteSheet.
Definition at line 16 of file fidgetSpinner.cpp.
{
  m_angle += m_rotationspeed *
             Engine::getInstance().getLastFrameDuration().asSeconds();
  setRotation(m_angle);
  if (m_rotationspeed > 0) {
    m_rotationspeed -= m_rotationResistance + m_rotationspeed / 500;
    if (m_rotationspeed < 0)
      m_rotationspeed = 0;
  }
}
References Engine::getInstance(), Engine::getLastFrameDuration(), m_angle, m_rotationResistance, and m_rotationspeed.
getCenterPoint()
Point2d FidgetSpinner::getCenterPoint () const
Definition at line 28 of file fidgetSpinner.cpp.
{
  Point2d point{getCurrentAnimationFrameData().m_position +
                getCurrentAnimationFrameData().m_size * 0.5};
  return point;
}
References AnimatedSpriteSheet::getCurrentAnimationFrameData(), AnimatedSpriteSheet::AnimationFrameData::m_position, and AnimatedSpriteSheet::AnimationFrameData::m_size.
getCurrentAnimationFrameCount()
int AnimatedSpriteSheet::getCurrentAnimationFrameCount () const protected inherited
Definition at line 54 of file animatedSpriteSheet.cpp.
{
  LOGTRACEN;
  return m_animationsData[m_currentAnimationTypeIndex].size();
}
References LOGTRACEN, AnimatedSpriteSheet::m_animationsData, and AnimatedSpriteSheet::m_currentAnimationTypeIndex.
Referenced by AnimatedSpriteSheet::nextFrame().
getCurrentAnimationFrameData()
const AnimatedSpriteSheet::AnimationFrameData & AnimatedSpriteSheet::getCurrentAnimationFrameData () const protected inherited
Definition at line 60 of file animatedSpriteSheet.cpp.
{
  LOGTRACEN;
  if (m_animationsData.size() == 0 ||
      m_animationsData.size() < m_currentAnimationTypeIndex) {
    LOGWARN << "No animation data\n";
  } else if (m_animationsData[m_currentAnimationTypeIndex].size() == 0 ||
             m_animationsData[m_currentAnimationTypeIndex].size() <
                 m_currentAnimationTypeIndex) {
    LOGWARN << "No frame data in animation " << m_currentAnimationTypeIndex
            << '\n';
  }
  return m_animationsData[m_currentAnimationTypeIndex][m_currentFrameId];
}
References LOGTRACEN, LOGWARN, AnimatedSpriteSheet::m_animationsData, AnimatedSpriteSheet::m_currentAnimationTypeIndex, and AnimatedSpriteSheet::m_currentFrameId.
Referenced by AnimatedSpriteSheet::AnimatedSpriteSheet(), getCenterPoint(), AnimatedSpriteSheet::getCurrentAnimationFrameDuration(), and AnimatedSpriteSheet::nextFrame().
getCurrentAnimationFrameDuration()
float AnimatedSpriteSheet::getCurrentAnimationFrameDuration () const protected inherited
Definition at line 74 of file animatedSpriteSheet.cpp.
{
  LOGTRACEN;
  return getCurrentAnimationFrameData().m_duration;
};
References AnimatedSpriteSheet::getCurrentAnimationFrameData(), LOGTRACEN, and AnimatedSpriteSheet::AnimationFrameData::m_duration.
Referenced by AnimatedSpriteSheet::animate().
getCurrentAnimationFrameRect()
sf::IntRect AnimatedSpriteSheet::getCurrentAnimationFrameRect () const protected inherited
getPosition()
Point2d GameObject::getPosition () const virtual inherited
Object position getter.
Definition at line 7 of file GameObject.cpp.
{ return m_position; }
References GameObject::m_position.
loadFrame()
void AnimatedSpriteSheet::loadFrame (std::istream & stream, animationData_t & animationData) protected inherited
load frame data from stream
Definition at line 85 of file animatedSpriteSheet.cpp.
{
  LOGTRACEN;
  // load Frame data
  AnimationFrameData fdat{};
  stream >> fdat;
  // LOGINFO << fdat.m_position << " " << fdat.m_size << " " <<
  // fdat.m_duration
  //         << '\n';
  // add frame data to animation
  animationData.push_back(fdat);
  stream.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
};
References LOGTRACEN.
Referenced by AnimatedSpriteSheet::loadFromConfigFile().
loadFromConfigFile()
void AnimatedSpriteSheet::loadFromConfigFile (std::string_view pathToDir) protected inherited
Definition at line 113 of file animatedSpriteSheet.cpp.
{
  std::string configFilePath{static_cast<std::string>(pathToDir) +
                             "/config.txt"};
  // open file
  std::fstream configFile{configFilePath};
  if (!configFile.is_open()) {
    LOGERROR << "opening config file failed it should be at " << configFilePath
             << "\n";
    return;
  }
  animationData_t *animationDataBeingLoaded{NULL};
  std::string line{};
  while (!configFile.eof()) {
    line = "";
    // load line, ignore lines that are commnets
    do {
      std::getline(configFile, line);
    } while (line.starts_with("#"));
    // load spritesheet
    if (line.starts_with("SPRITESHEET")) {
      loadSpritesheet(configFile, pathToDir);
    } else if (line.starts_with("ANIMATION")) {
      // Add new animation and change pointer
      //     LOGINFO << "loading animation data\n";
      m_animationsData.push_back({});
      animationDataBeingLoaded = {&m_animationsData.back()};
    }
    // load frame
    else if (line.starts_with("FRAME")) {
      if (animationDataBeingLoaded == NULL)
        LOGERROR << "config file is corrupted, FRAME before ANIMATION?";
      loadFrame(configFile, *animationDataBeingLoaded);
    }
    // not known
    else {
      // empty line ignore
      if (line == "") {
        continue;
      }
      // invalid line
      LOGWARN << "not recegnized config option: " << line
              << " in file: " << configFilePath << '\n';
    }
  }
  // close file
  configFile.close();
}
References AnimatedSpriteSheet::loadFrame(), AnimatedSpriteSheet::loadSpritesheet(), LOGERROR, LOGWARN, and AnimatedSpriteSheet::m_animationsData.
Referenced by AnimatedSpriteSheet::AnimatedSpriteSheet().
loadSpritesheet()
void AnimatedSpriteSheet::loadSpritesheet (std::istream & stream, std::string_view configFileDirectoryPath) protected inherited
Definition at line 100 of file animatedSpriteSheet.cpp.
{
  LOGINFO << "loading spritesheet data\n";
  std::string spriteSheetRelPath{};
  stream >> spriteSheetRelPath;
  spriteSheetRelPath =
      std::string(configFileDirectoryPath) + "/" + spriteSheetRelPath;
  loadFromFile(spriteSheetRelPath);
  stream.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
}
References LOGINFO.
Referenced by AnimatedSpriteSheet::loadFromConfigFile().
move()
void AnimatedObject::move (Point2d vector) virtual inherited
Translates object in space.
Parameters
vector 2D vector added to current object position.
Reimplemented from GameObject.
Reimplemented in Player.
Definition at line 14 of file animatedObject.cpp.
{
  GameObject::move(vec);
  sf::Sprite::move(vec.toVector2f());
  // LOGINFO << GameObject::getPosition() << '\n';
};
References GameObject::move(), and Point2d::toVector2f().
nextFrame()
void AnimatedSpriteSheet::nextFrame () protected inherited
Definition at line 46 of file animatedSpriteSheet.cpp.
{
  LOGTRACEN;
  // change frame
  ++m_currentFrameId;
  m_currentFrameId %= getCurrentAnimationFrameCount();
  setFrame(getCurrentAnimationFrameData());
}
References AnimatedSpriteSheet::getCurrentAnimationFrameCount(), AnimatedSpriteSheet::getCurrentAnimationFrameData(), LOGTRACEN, AnimatedSpriteSheet::m_currentFrameId, and AnimatedSpriteSheet::setFrame().
Referenced by AnimatedSpriteSheet::animate().
setFrame()
void AnimatedSpriteSheet::setFrame (const AnimationFrameData & frameData) protected inherited
Definition at line 79 of file animatedSpriteSheet.cpp.
{
  LOGTRACEN;
  setTextureRect(frameData.toIntRect());
  m_animationTimer = 0;
}
References LOGTRACEN, AnimatedSpriteSheet::m_animationTimer, and AnimatedSpriteSheet::AnimationFrameData::toIntRect().
Referenced by AnimatedSpriteSheet::AnimatedSpriteSheet(), and AnimatedSpriteSheet::nextFrame().
setPosition()
void AnimatedObject::setPosition (Point2d pos) virtual inherited
Object position setter.
Parameters
pos Position to be set.
Reimplemented from GameObject.
Definition at line 9 of file animatedObject.cpp.
{
  GameObject::setPosition(pos);
  sf::Sprite::setPosition(pos.toVector2f());
};
References GameObject::setPosition(), and Point2d::toVector2f().
Referenced by initializeFidgetSpinner(), and main().
setRotationResistance()
void FidgetSpinner::setRotationResistance (float speed)
Definition at line 37 of file fidgetSpinner.cpp.
{
  m_rotationResistance = speed;
}
References m_rotationResistance.
Member Data Documentation
m_angle
float FidgetSpinner::m_angle {} private
Definition at line 24 of file fidgetSpinner.hpp.
{};
Referenced by animate().
m_animationsData
std::vector<animationData_t> AnimatedSpriteSheet::m_animationsData private inherited
Colecction of animations.
Definition at line 55 of file animatedSpriteSheet.hpp.
Referenced by AnimatedSpriteSheet::getCurrentAnimationFrameCount(), AnimatedSpriteSheet::getCurrentAnimationFrameData(), and AnimatedSpriteSheet::loadFromConfigFile().
m_animationTimer
float AnimatedSpriteSheet::m_animationTimer {} private inherited
Definition at line 63 of file animatedSpriteSheet.hpp.
{};
Referenced by AnimatedSpriteSheet::animate(), and AnimatedSpriteSheet::setFrame().
m_currentAnimationTypeIndex
int AnimatedSpriteSheet::m_currentAnimationTypeIndex private inherited
Indicates index of current animation in m_animationsData.
Definition at line 60 of file animatedSpriteSheet.hpp.
Referenced by AnimatedSpriteSheet::getCurrentAnimationFrameCount(), and AnimatedSpriteSheet::getCurrentAnimationFrameData().
m_currentFrameId
int AnimatedSpriteSheet::m_currentFrameId {} private inherited
Definition at line 61 of file animatedSpriteSheet.hpp.
{};
Referenced by AnimatedSpriteSheet::getCurrentAnimationFrameData(), and AnimatedSpriteSheet::nextFrame().
m_position
Point2d GameObject::m_position {} private inherited
Position of object on screen.
Definition at line 14 of file GameObject.hpp.
{};
Referenced by GameObject::getPosition(), GameObject::move(), and GameObject::setPosition().
m_rotationResistance
float FidgetSpinner::m_rotationResistance {0.1} private
Definition at line 22 of file fidgetSpinner.hpp.
{0.1};
Referenced by animate(), and setRotationResistance().
m_rotationspeed
float FidgetSpinner::m_rotationspeed {0} private
Definition at line 23 of file fidgetSpinner.hpp.
{0};
Referenced by addRotationSpeed(), and animate().
The documentation for this class was generated from the following files:
fidgetSpinner.hpp
fidgetSpinner.cpp