Podstawy grafiki komputerowej: GamePlayer Class Reference
GamePlayer Class Reference
#include <gamePlayer.hpp>
Public Types
enum class AnimationType {
standing , moveNorth , moveEast , moveSouth ,
moveWest , moveSpecial , count
}
enum class MoveDirection {
north , east , south , west ,
count
}
Directions of movement.
Public Member Functions
GamePlayer ()
virtual void animate () override
Animates object.
virtual void update () override
Updates state of object.
virtual void setIsMoving (MoveDirection direction)
virtual void stopMoving (MoveDirection direction)
void stopMoving ()
Stops player from moving.
bool isMoving () const
Checks if player is moving.
bool isMoving (MoveDirection direction) const
Checks if player is moving in a specific direction.
void setMovementSpeed (float speed)
Player movement speed setter.
virtual float getMovementSpeed () const
Player movement speed getter.
bool isMovingDiagonaly () const
Checks if player is moving diagonally.
Point2d getMoveVectorOrigin () const
Returns a 2D vector containing information on which cardinal directions the player is moving.
Point2d getMoveVector () const
Returns the player's movement vector multiplied by speed.
virtual void setPosition (Point2d pos)
Object position setter.
virtual Point2d getPosition () const
Object position getter.
Static Public Attributes
static constexpr std::string_view s_spriteSheetPath
Private Member Functions
void nextAnimationFrame ()
void updateTextureRect ()
void setAnimationType (AnimationType type)
AnimationType getAnimationTypeOf (MoveDirection moveDirection) const
int getFrameCountOfAnimation (AnimationType type) const
sf::IntRect getCurrentAnimationFrameSpriteRectangle () const
int getRowOfAnimation () const
void move (Point2d vec)
Moves player on screen.
Private Attributes
int m_aninmationFrameIndicator {}
float m_animationFrameDuration {.5}
float m_animationTimer {}
AnimationType m_animationType {AnimationType::standing}
float m_movementSpeed {50}
Player movement speed.
std::array< bool, static_cast< ssize_t >(MoveDirection::count)> m_isMoving {}
Array with player's current movement direction.
Point2d m_position {}
Position of object on screen.
Detailed Description
Definition at line 10 of file gamePlayer.hpp.
Member Enumeration Documentation
AnimationType
enum class GamePlayer::AnimationType strong
Enumerator
standing
moveNorth
moveEast
moveSouth
moveWest
moveSpecial
count
Definition at line 15 of file gamePlayer.hpp.
{
    standing,
    moveNorth,
    moveEast,
    moveSouth,
    moveWest,
    moveSpecial,
    count
  };
MoveDirection
enum class Player::MoveDirection strong inherited
Directions of movement.
Enumerator
north
east
south
west
count
Definition at line 21 of file player.hpp.
{ north, east, south, west, count };
Constructor & Destructor Documentation
GamePlayer()
GamePlayer::GamePlayer ()
Definition at line 15 of file gamePlayer.cpp.
                       {
  LOGINFON;
  loadFromFile(
      std::string(s_spriteSheetPath),
      sf::IntRect{0, 0, 4 * 300, static_cast<int>(AnimationType::count) * 300});
  setTexture(*this);
  setTextureRect(getCurrentAnimationFrameSpriteRectangle());
}
References count, getCurrentAnimationFrameSpriteRectangle(), LOGINFON, and s_spriteSheetPath.
Member Function Documentation
animate()
void GamePlayer::animate () override virtual
Animates object.
Reimplemented from AnimatedObject.
Definition at line 31 of file gamePlayer.cpp.
{
  m_animationTimer += Engine::getInstance().getLastFrameDuration().asSeconds();
  // wait for next frame change
  if (m_animationTimer < m_animationFrameDuration)
    return;
  // reset timer
  m_animationTimer = 0;
  // do frame changing
  nextAnimationFrame();
}
References Engine::getInstance(), Engine::getLastFrameDuration(), m_animationFrameDuration, m_animationTimer, and nextAnimationFrame().
getAnimationTypeOf()
GamePlayer::AnimationType GamePlayer::getAnimationTypeOf (MoveDirection moveDirection) const private
Definition at line 99 of file gamePlayer.cpp.
{
  switch (moveDirection) {
  case Player::MoveDirection::north:
    return AnimationType::moveNorth;
  case Player::MoveDirection::east:
    return AnimationType::moveEast;
  case Player::MoveDirection::south:
    return AnimationType::moveSouth;
  case Player::MoveDirection::west:
    return AnimationType::moveWest;
  default:
    LOGWARN << "UNHANDLED\n";
    break;
  }
  return AnimationType::standing;
}
References Player::east, LOGWARN, moveEast, moveNorth, moveSouth, moveWest, Player::north, Player::south, standing, and Player::west.
Referenced by update().
getCurrentAnimationFrameSpriteRectangle()
sf::IntRect GamePlayer::getCurrentAnimationFrameSpriteRectangle () const private
Definition at line 24 of file gamePlayer.cpp.
{
  sf::IntRect result{m_aninmationFrameIndicator * 300,
                     getRowOfAnimation() * 300, 300, 300};
  // LOGINFO << result.top << '\t' << result.left << '\n';
  return result;
}
References getRowOfAnimation(), and m_aninmationFrameIndicator.
Referenced by GamePlayer(), and updateTextureRect().
getFrameCountOfAnimation()
int GamePlayer::getFrameCountOfAnimation (AnimationType type) const private
Definition at line 67 of file gamePlayer.cpp.
{
  switch (type) {
  case AnimationType::standing:
    return 4;
  case AnimationType::moveNorth:
    return 4;
  case AnimationType::moveEast:
    return 4;
  case AnimationType::moveSouth:
    return 4;
  case AnimationType::moveWest:
    return 4;
  case AnimationType::moveSpecial:
    return 4;
  default:
    LOGWARN << "Animation type not handled!\n";
    return 0;
    break;
  }
}
References LOGWARN, moveEast, moveNorth, moveSouth, moveSpecial, moveWest, and standing.
Referenced by nextAnimationFrame().
getMovementSpeed()
float Player::getMovementSpeed () const virtual inherited
Player movement speed getter.
Definition at line 32 of file player.cpp.
{ return m_movementSpeed; };
References Player::m_movementSpeed.
getMoveVector()
Point2d Player::getMoveVector () const inherited
Returns the player's movement vector multiplied by speed.
Definition at line 40 of file player.cpp.
{
  return getMoveVectorOrigin() * m_movementSpeed *
         Engine::getInstance().getLastFrameDuration().asSeconds();
}
References Engine::getInstance(), Engine::getLastFrameDuration(), Player::getMoveVectorOrigin(), and Player::m_movementSpeed.
Referenced by Player::move(), and Player::update().
getMoveVectorOrigin()
Point2d Player::getMoveVectorOrigin () const inherited
Returns a 2D vector containing information on which cardinal directions the player is moving.
Definition at line 17 of file player.cpp.
{
  Point2d vec{};
  if (m_isMoving[static_cast<int>(MoveDirection::north)])
    vec += {0, -1};
  if (m_isMoving[static_cast<int>(MoveDirection::east)])
    vec += {1, 0};
  if (m_isMoving[static_cast<int>(MoveDirection::south)])
    vec += {0, 1};
  if (m_isMoving[static_cast<int>(MoveDirection::west)])
    vec += {-1, 0};
  return vec;
}
References Player::east, Player::m_isMoving, Player::north, Player::south, and Player::west.
Referenced by Player::getMoveVector(), Player::isMoving(), Player::isMovingDiagonaly(), and throwBallPlayer().
getPosition()
Point2d GameObject::getPosition () const virtual inherited
Object position getter.
Definition at line 7 of file GameObject.cpp.
{ return m_position; }
References GameObject::m_position.
getRowOfAnimation()
int GamePlayer::getRowOfAnimation () const private
Definition at line 128 of file gamePlayer.cpp.
{
  switch (m_animationType) {
  case AnimationType::standing:
    return 0;
  case AnimationType::moveNorth:
    return 1;
  case AnimationType::moveEast:
    return 2;
  case AnimationType::moveSouth:
    return 3;
  case AnimationType::moveWest:
    return 4;
  case AnimationType::moveSpecial:
    return 5;
  default:
    LOGWARN << "not handled\n";
    return 0;
  };
};
References LOGWARN, m_animationType, moveEast, moveNorth, moveSouth, moveSpecial, moveWest, and standing.
Referenced by getCurrentAnimationFrameSpriteRectangle().
isMoving() [1/2]
bool Player::isMoving () const inherited
Checks if player is moving.
Definition at line 53 of file player.cpp.
{
  bool moving{};
  return getMoveVectorOrigin() != Point2d{0, 0};
}
References Player::getMoveVectorOrigin().
Referenced by update().
isMoving() [2/2]
bool Player::isMoving (MoveDirection direction) const inherited
Checks if player is moving in a specific direction.
Parameters
direction Direction checked.
Definition at line 58 of file player.cpp.
{
  return m_isMoving[static_cast<ssize_t>(direction)];
}
References Player::m_isMoving.
isMovingDiagonaly()
bool Player::isMovingDiagonaly () const inherited
Checks if player is moving diagonally.
Definition at line 34 of file player.cpp.
{
  Point2d vec{getMoveVectorOrigin()};
  auto absMoveDist{std::abs(vec.getX()) + std::abs(vec.getY())};
  return absMoveDist > 1;
}
References Player::getMoveVectorOrigin().
Referenced by update().
move()
void Player::move (Point2d vec) private virtual inherited
Moves player on screen.
Parameters
vec Vector by which player is moved.
Reimplemented from AnimatedObject.
Definition at line 11 of file player.cpp.
{
  GameObject::move(vec);
  sf::Sprite::move(getMoveVector().toVector2f());
  // LOGINFO << GameObject::getPosition() << '\n';
};
References Player::getMoveVector(), and GameObject::move().
Referenced by Player::update().
nextAnimationFrame()
void GamePlayer::nextAnimationFrame () private
Definition at line 116 of file gamePlayer.cpp.
{
  updateTextureRect();
  ++m_aninmationFrameIndicator;
  m_aninmationFrameIndicator %= getFrameCountOfAnimation(m_animationType);
  // LOGINFO << "Frame: " << m_aninmationFrameIndicator
  //         << " Type: " << static_cast<int>(m_animationType) << '\n';
};
References getFrameCountOfAnimation(), m_animationType, m_aninmationFrameIndicator, and updateTextureRect().
Referenced by animate(), and setAnimationType().
setAnimationType()
void GamePlayer::setAnimationType (GamePlayer::AnimationType type) private
Definition at line 88 of file gamePlayer.cpp.
{
  // Do no reset current animation if new is same.
  if (type == m_animationType)
    return;
  m_animationType = type;
  m_aninmationFrameIndicator = 0;
  m_animationTimer = 0;
  nextAnimationFrame();
};
References m_animationTimer, m_animationType, m_aninmationFrameIndicator, and nextAnimationFrame().
Referenced by update().
setIsMoving()
void Player::setIsMoving (MoveDirection direction) virtual inherited
Parameters
direction
Definition at line 45 of file player.cpp.
{
  m_isMoving[static_cast<ssize_t>(direction)] = true;
};
References Player::m_isMoving.
Referenced by keyPressedEventHandler().
setMovementSpeed()
void Player::setMovementSpeed (float speed) inherited
Player movement speed setter.
Definition at line 31 of file player.cpp.
{ m_movementSpeed = speed; }
References Player::m_movementSpeed.
Referenced by initialziePlayer().
setPosition()
void AnimatedObject::setPosition (Point2d pos) virtual inherited
Object position setter.
Parameters
pos Position to be set.
Reimplemented from GameObject.
Definition at line 9 of file animatedObject.cpp.
{
  GameObject::setPosition(pos);
  sf::Sprite::setPosition(pos.toVector2f());
};
References GameObject::setPosition(), and Point2d::toVector2f().
Referenced by initializeFidgetSpinner(), and main().
stopMoving() [1/2]
void Player::stopMoving () inherited
Stops player from moving.
Definition at line 62 of file player.cpp.
{
  for (auto &it : m_isMoving) {
    it = false;
  }
}
References Player::m_isMoving.
stopMoving() [2/2]
void Player::stopMoving (MoveDirection direction) virtual inherited
Parameters
direction
Definition at line 49 of file player.cpp.
{
  m_isMoving[static_cast<ssize_t>(direction)] = false;
}
References Player::m_isMoving.
Referenced by keyReleasedEventHandler().
update()
void GamePlayer::update () override virtual
Updates state of object.
Reimplemented from Player.
Definition at line 42 of file gamePlayer.cpp.
{
  Player::update();
  // Handle animation update
  AnimationType animation = AnimationType::standing;
  if (isMoving()) {
    // if is moving diagonally
    if (isMovingDiagonaly()) {
      animation = AnimationType::moveSpecial;
    } else {
      // check if is moving in any single direction
      for (int i{}; i < static_cast<int>(MoveDirection::count); ++i) {
        MoveDirection moveDir{static_cast<MoveDirection>(i)};
        if (isMoving(moveDir)) {
          animation = getAnimationTypeOf(moveDir);
          break;
        }
      }
    }
  }
  setAnimationType(animation);
}
References animation, Player::count, getAnimationTypeOf(), Player::isMoving(), Player::isMovingDiagonaly(), moveSpecial, setAnimationType(), standing, and Player::update().
Referenced by handlePlayerMovement().
updateTextureRect()
void GamePlayer::updateTextureRect () private
Definition at line 124 of file gamePlayer.cpp.
{
  this->setTextureRect(getCurrentAnimationFrameSpriteRectangle());
}
References getCurrentAnimationFrameSpriteRectangle().
Referenced by nextAnimationFrame().
Member Data Documentation
m_animationFrameDuration
float GamePlayer::m_animationFrameDuration {.5} private
Definition at line 33 of file gamePlayer.hpp.
{.5};
Referenced by animate().
m_animationTimer
float GamePlayer::m_animationTimer {} private
Definition at line 34 of file gamePlayer.hpp.
{};
Referenced by animate(), and setAnimationType().
m_animationType
AnimationType GamePlayer::m_animationType {AnimationType::standing} private
Definition at line 35 of file gamePlayer.hpp.
{AnimationType::standing};
Referenced by getRowOfAnimation(), nextAnimationFrame(), and setAnimationType().
m_aninmationFrameIndicator
int GamePlayer::m_aninmationFrameIndicator {} private
Definition at line 32 of file gamePlayer.hpp.
{};
Referenced by getCurrentAnimationFrameSpriteRectangle(), nextAnimationFrame(), and setAnimationType().
m_isMoving
std::array<bool, static_cast<ssize_t>(MoveDirection::count)> Player::m_isMoving {} private inherited
Array with player's current movement direction.
Definition at line 31 of file player.hpp.
{};
Referenced by Player::getMoveVectorOrigin(), Player::isMoving(), Player::setIsMoving(), Player::stopMoving(), and Player::stopMoving().
m_movementSpeed
float Player::m_movementSpeed {50} private inherited
Player movement speed.
Definition at line 27 of file player.hpp.
{50};
Referenced by Player::getMovementSpeed(), Player::getMoveVector(), and Player::setMovementSpeed().
m_position
Point2d GameObject::m_position {} private inherited
Position of object on screen.
Definition at line 14 of file GameObject.hpp.
{};
Referenced by GameObject::getPosition(), GameObject::move(), and GameObject::setPosition().
s_spriteSheetPath
constexpr std::string_view GamePlayer::s_spriteSheetPath static constexpr
Initial value:
{
      "resource/player/spritesheet.png"}
Definition at line 12 of file gamePlayer.hpp.
{
      "resource/player/spritesheet.png"};
Referenced by GamePlayer().
The documentation for this class was generated from the following files:
gamePlayer.hpp
gamePlayer.cpp