Podstawy grafiki komputerowej: Point2d Class Reference
Point2d Class Reference
Class containing 2D point co-ordinates.
#include <point2d.hpp>
Public Types
using cordinate_t = float
Public Member Functions
Point2d (cordinate_t x=0, cordinate_t y=0)
Constructor.
Point2d (const Point2d &point)=default
Copy constructor.
Point2d (const sf::Vector2f &vector)
Constructor.
Point2d (const sf::Vector2i &vector)
cordinate_t getX () const
X co-ordinate getter.
cordinate_t getY () const
Y co-ordinate getter.
void setX (cordinate_t x)
X co-ordinate setter.
void setY (cordinate_t y)
Y co-ordinate setter.
void swap (Point2d &b)
Swaps co-ordinates with another point.
sf::Vector2f toVector2f () const
Convert to Vector2f.
cordinate_t length () const
Get length of vector.
cordinate_t distanceTo (const Point2d &point) const
Get distance between two points.
Private Attributes
cordinate_t m_x
X co-ordinate of the point.
cordinate_t m_y
Y co-ordinate of the point.
Friends
Point2d operator+ (const Point2d &a, const Point2d &b)
Point2d & operator+= (Point2d &a, const Point2d &b)
Point2d operator- (const Point2d &a, const Point2d &b)
bool operator== (const Point2d &a, const Point2d &b)
bool operator!= (const Point2d &a, const Point2d &b)
Point2d operator* (const Point2d &a, float b)
Point2d operator* (float b, const Point2d &a)
std::ostream & operator<< (std::ostream &os, const Point2d &point)
std::istream & operator>> (std::istream &is, Point2d &point)
Detailed Description
Class containing 2D point co-ordinates.
Definition at line 9 of file point2d.hpp.
Member Typedef Documentation
cordinate_t
using Point2d::cordinate_t = float
Definition at line 11 of file point2d.hpp.
Constructor & Destructor Documentation
Point2d() [1/4]
Point2d::Point2d (cordinate_t x = 0, cordinate_t y = 0)
Constructor.
Parameters
x X co-ordinate of point.
y Y co-ordinate of point.
Definition at line 10 of file point2d.cpp.
: m_x(x), m_y(y){};
Point2d() [2/4]
Point2d::Point2d (const Point2d & point) default
Copy constructor.
Parameters
point Instance of class Point2d.
Point2d() [3/4]
Point2d::Point2d (const sf::Vector2f & vector) explicit
Constructor.
Parameters
vector 2D vector.
Definition at line 11 of file point2d.cpp.
: m_x{vector.x}, m_y{vector.y} {};
Point2d() [4/4]
Point2d::Point2d (const sf::Vector2i & vector) explicit
Definition at line 12 of file point2d.cpp.
    : m_x{static_cast<cordinate_t>(vector.x)},
      m_y{static_cast<cordinate_t>(vector.y)} {};
Member Function Documentation
distanceTo()
Point2d::cordinate_t Point2d::distanceTo (const Point2d & point) const
Get distance between two points.
Parameters
point Point to which distance is calculated.
Definition at line 77 of file point2d.cpp.
{
  return (*this - point).length();
};
getX()
Point2d::cordinate_t Point2d::getX () const
X co-ordinate getter.
Definition at line 54 of file point2d.cpp.
{ return m_x; };
References m_x.
Referenced by Engine::buildWindow(), Engine::handleEvents(), and AnimatedSpriteSheet::AnimationFrameData::toIntRect().
getY()
Point2d::cordinate_t Point2d::getY () const
Y co-ordinate getter.
Definition at line 55 of file point2d.cpp.
{ return m_y; };
References m_y.
Referenced by Engine::buildWindow(), Engine::handleEvents(), and AnimatedSpriteSheet::AnimationFrameData::toIntRect().
length()
Point2d::cordinate_t Point2d::length () const
Get length of vector.
Definition at line 72 of file point2d.cpp.
{
  return std::sqrt((m_x * m_x) + (m_y * m_y));
  return length();
}
References length(), m_x, and m_y.
Referenced by length().
setX()
void Point2d::setX (cordinate_t x)
X co-ordinate setter.
Definition at line 57 of file point2d.cpp.
{ m_x = x; };
References m_x.
Referenced by Engine::handleEvents().
setY()
void Point2d::setY (cordinate_t y)
Y co-ordinate setter.
Definition at line 58 of file point2d.cpp.
{ m_y = y; };
References m_y.
Referenced by Engine::handleEvents().
swap()
void Point2d::swap (Point2d & b)
Swaps co-ordinates with another point.
Parameters
b Point to swap co-ordinates with.
Definition at line 63 of file point2d.cpp.
{
  std::swap(m_x, b.m_x);
  std::swap(m_y, b.m_y);
}
References m_x, and m_y.
toVector2f()
sf::Vector2f Point2d::toVector2f () const
Convert to Vector2f.
Definition at line 68 of file point2d.cpp.
{
  return {static_cast<float>(m_x), static_cast<float>(m_y)};
}
References m_x, and m_y.
Referenced by FidgetSpinner::FidgetSpinner(), obstacle::LineSegment::LineSegment(), AnimatedObject::move(), Ball::move(), obstacle::LineSegment::setEnd(), AnimatedObject::setPosition(), Ball::setPositon(), and obstacle::LineSegment::setStart().
Friends And Related Symbol Documentation
operator!=
bool operator!= (const Point2d & a, const Point2d & b) friend
Definition at line 50 of file point2d.cpp.
{
  return !operator==(a, b);
}
operator* [1/2]
Point2d operator* (const Point2d & a, float b) friend
Definition at line 29 of file point2d.cpp.
{
  return {a.getX() * b, a.getY() * b};
};
operator* [2/2]
Point2d operator* (float b, const Point2d & a) friend
Definition at line 33 of file point2d.cpp.
{ return operator*(a, b); }
operator+
Point2d operator+ (const Point2d & a, const Point2d & b) friend
Definition at line 16 of file point2d.cpp.
{
  return {a.m_x + b.m_x, a.m_y + b.m_y};
}
operator+=
Point2d & operator+= (Point2d & a, const Point2d & b) friend
Definition at line 20 of file point2d.cpp.
{
  a = a + b;
  return a;
}
operator-
Point2d operator- (const Point2d & a, const Point2d & b) friend
Definition at line 25 of file point2d.cpp.
{
  return operator+(a, -1 * b);
}
operator<<
std::ostream & operator<< (std::ostream & os, const Point2d & point) friend
Definition at line 35 of file point2d.cpp.
{
  os << "Point2d(" << point.m_x << ", " << point.m_y << ")";
  return os;
}
operator==
bool operator== (const Point2d & a, const Point2d & b) friend
Definition at line 46 of file point2d.cpp.
{
  return a.getX() == b.getX() && a.getY() == b.getY();
}
operator>>
std::istream & operator>> (std::istream & is, Point2d & point) friend
Definition at line 40 of file point2d.cpp.
{
  is >> point.m_x;
  is >> point.m_y;
  return is;
}
Member Data Documentation
m_x
cordinate_t Point2d::m_x private
X co-ordinate of the point.
Definition at line 17 of file point2d.hpp.
Referenced by getX(), length(), setX(), swap(), and toVector2f().
m_y
cordinate_t Point2d::m_y private
Y co-ordinate of the point.
Definition at line 21 of file point2d.hpp.
Referenced by getY(), length(), setY(), swap(), and toVector2f().
The documentation for this class was generated from the following files:
point2d.hpp
point2d.cpp