Podstawy grafiki komputerowej: main.cpp File Reference
main.cpp File Reference
#include "SFML/Graphics/Color.hpp"
#include "SFML/Graphics/Rect.hpp"
#include "SFML/Graphics/Sprite.hpp"
#include "SFML/Graphics/Texture.hpp"
#include "SFML/System/Vector2.hpp"
#include "SFML/Window/Event.hpp"
#include "SFML/Window/Keyboard.hpp"
#include "animatedObject.hpp"
#include "animatedSpriteSheet.hpp"
#include "ball.hpp"
#include "bush.hpp"
#include "engine.hpp"
#include "fidgetSpinner.hpp"
#include "gamePlayer.hpp"
#include "log.hpp"
#include "player.hpp"
#include "point2d.hpp"
#include <cstdlib>
#include <iostream>
#include <list>
#include <random>
#include <utility>
Functions
Ball * throwBall (Point2d pos, Point2d vector)
sf::Color getRandomColor ()
void throwBallPlayer ()
void initialziePlayer ()
void initializeBush ()
void handlePlayerMovement ()
void handleBalls ()
void customLoop ()
void spinTheFidget ()
void keyPressedEventHandler (const sf::Event &ev)
void keyReleasedEventHandler (const sf::Event &ev)
void initializeFidgetSpinner ()
int main ()
Variables
GamePlayer player {}
std::array< Bush, 4 > bush {}
Engine & eng = Engine::getInstance()
FidgetSpinner fidgetSpinner {"resource/fidgetSpinner"}
std::list< Ball * > balls
Function Documentation
customLoop()
void customLoop ()
Definition at line 94 of file test2/main.cpp.
                  {
  handlePlayerMovement();
  handleBalls();
}
References handleBalls(), and handlePlayerMovement().
Referenced by main().
getRandomColor()
sf::Color getRandomColor ()
Definition at line 41 of file test2/main.cpp.
{
  return {static_cast<sf::Uint8>(rand() % 256),
          static_cast<sf::Uint8>(rand() % 256),
          static_cast<sf::Uint8>(rand() % 256)};
}
Referenced by throwBallPlayer().
handleBalls()
void handleBalls ()
Definition at line 79 of file test2/main.cpp.
                   {
  for (auto it{balls.begin()}; it != balls.end();) {
    auto it2{it};
    ++it;
    Ball *b = *it2;
    b->update();
    if (b->isDead()) {
      Engine::getInstance().remove(b);
      balls.remove(b);
      delete b;
    }
  }
}
References balls, Engine::getInstance(), Ball::isDead(), Engine::remove(), and Ball::update().
Referenced by customLoop().
handlePlayerMovement()
void handlePlayerMovement ()
Definition at line 77 of file test2/main.cpp.
{ player.update(); }
References player, and GamePlayer::update().
Referenced by customLoop().
initializeBush()
void initializeBush ()
Definition at line 66 of file test2/main.cpp.
                      {
  for (ssize_t i{}; i < bush.max_size(); ++i) {
    LOGINFO << i << '\n';
    eng.add(&(bush[i]));
  }
  bush[0].setPosition({300, 150});
  bush[1].setPosition({700, 550});
  bush[2].setPosition({100, 450});
  bush[3].setPosition({800, 250});
}
References Engine::add(), bush, eng, and LOGINFO.
Referenced by main().
initializeFidgetSpinner()
void initializeFidgetSpinner ()
Definition at line 163 of file test2/main.cpp.
{
  fidgetSpinner.setPosition({600, 600});
  eng.add(&fidgetSpinner);
}
References Engine::add(), eng, fidgetSpinner, and AnimatedObject::setPosition().
Referenced by main().
initialziePlayer()
void initialziePlayer ()
Definition at line 59 of file test2/main.cpp.
{
  LOGINFON;
  player.setMovementSpeed(50);
  player.setColor(sf::Color::Yellow);
  eng.add(&player);
}
References Engine::add(), eng, LOGINFON, player, and Player::setMovementSpeed().
Referenced by main().
keyPressedEventHandler()
void keyPressedEventHandler (const sf::Event & ev)
Definition at line 114 of file test2/main.cpp.
{
  switch (ev.key.code) {
  case sf::Keyboard::W:
    player.setIsMoving(Player::MoveDirection::north);
    break;
  case sf::Keyboard::A:
    player.setIsMoving(Player::MoveDirection::west);
    break;
  case sf::Keyboard::S:
    player.setIsMoving(Player::MoveDirection::south);
    break;
  case sf::Keyboard::D:
    player.setIsMoving(Player::MoveDirection::east);
    break;
  case sf::Keyboard::F:
    throwBallPlayer();
    break;
  case sf::Keyboard::Space:
    spinTheFidget();
    break;
  case sf::Keyboard::Escape:
    eng.getWindow().close();
    break;
  default:
    break;
  }
}
References Player::east, eng, Engine::getWindow(), Player::north, player, Player::setIsMoving(), Player::south, spinTheFidget(), throwBallPlayer(), and Player::west.
Referenced by main().
keyReleasedEventHandler()
void keyReleasedEventHandler (const sf::Event & ev)
Definition at line 144 of file test2/main.cpp.
{
  switch (ev.key.code) {
  case sf::Keyboard::W:
    player.stopMoving(Player::MoveDirection::north);
    break;
  case sf::Keyboard::A:
    player.stopMoving(Player::MoveDirection::west);
    break;
  case sf::Keyboard::S:
    player.stopMoving(Player::MoveDirection::south);
    break;
  case sf::Keyboard::D:
    player.stopMoving(Player::MoveDirection::east);
    break;
  default:
    break;
  }
}
References Player::east, Player::north, player, Player::south, Player::stopMoving(), and Player::west.
Referenced by main().
main()
int main ()
Definition at line 168 of file test2/main.cpp.
           {
  LOGTRACEN;
  eng.setWindowTitle("dev").setMaxFps(75).buildWindow();
  eng.setEventHandler(sf::Event::KeyPressed, keyPressedEventHandler);
  eng.setEventHandler(sf::Event::KeyReleased, keyReleasedEventHandler);
  eng.setLoopFunction(customLoop);
  initialziePlayer();
  initializeBush();
  initializeFidgetSpinner();
  throwBall({100, 0}, {1, 1});
  eng.loop();
}
References Engine::buildWindow(), customLoop(), eng, initializeBush(), initializeFidgetSpinner(), initialziePlayer(), keyPressedEventHandler(), keyReleasedEventHandler(), LOGTRACEN, Engine::loop(), Engine::setEventHandler(), Engine::setLoopFunction(), Engine::setMaxFps(), Engine::setWindowTitle(), and throwBall().
spinTheFidget()
void spinTheFidget ()
Definition at line 99 of file test2/main.cpp.
                     {
  Point2d pla{Point2d(player.sf::Sprite::getPosition()) +
              Point2d{player.sf::Sprite::getTextureRect().getSize()} * 0.5};
  Point2d fig{Point2d{fidgetSpinner.sf::Sprite::getPosition()} +
              Point2d{fidgetSpinner.getTextureRect().getSize()} * 0.5};
  float dist(pla.distanceTo(fig));
  LOGINFO << dist << '\n';
  if (dist < 300) {
    fidgetSpinner.addRotationSpeed(8);
  }
}
References FidgetSpinner::addRotationSpeed(), fidgetSpinner, LOGINFO, and player.
Referenced by keyPressedEventHandler().
throwBall()
Ball * throwBall (Point2d pos, Point2d vector)
Definition at line 32 of file test2/main.cpp.
{
  Ball *bal = new Ball();
  bal->setPositon(pos);
  bal->setMoveVectorBase(vector);
  balls.push_back(bal);
  eng.add(bal);
  return bal;
}
References Engine::add(), balls, eng, Ball::setMoveVectorBase(), and Ball::setPositon().
Referenced by main(), and throwBallPlayer().
throwBallPlayer()
void throwBallPlayer ()
Definition at line 47 of file test2/main.cpp.
                       {
  Ball *bal{throwBall(
      static_cast<Point2d>(
          player.GameObject::getPosition() +
          static_cast<Point2d>(player.sf::Sprite::getTextureRect().getSize()) *
              0.5),
      player.getMoveVectorOrigin())};
  bal->setMovementSpeed(80);
  bal->setFillColor(getRandomColor());
}
References Player::getMoveVectorOrigin(), getRandomColor(), player, Ball::setMovementSpeed(), and throwBall().
Referenced by keyPressedEventHandler().
Variable Documentation
balls
std::list<Ball *> balls
Definition at line 30 of file test2/main.cpp.
Referenced by handleBalls(), and throwBall().
bush
std::array<Bush, 4> bush {}
Definition at line 27 of file test2/main.cpp.
{};
Referenced by initializeBush().
eng
Engine& eng = Engine::getInstance()
Definition at line 28 of file test2/main.cpp.
Referenced by addSomeRenderables(), initializeBush(), initializeFidgetSpinner(), initialziePlayer(), keyPressedEventHandler(), main(), and throwBall().
fidgetSpinner
FidgetSpinner fidgetSpinner {"resource/fidgetSpinner"}
Definition at line 29 of file test2/main.cpp.
{"resource/fidgetSpinner"};
Referenced by initializeFidgetSpinner(), and spinTheFidget().
player
GamePlayer player {}
Definition at line 26 of file test2/main.cpp.
{};
Referenced by handlePlayerMovement(), initialziePlayer(), keyPressedEventHandler(), keyReleasedEventHandler(), spinTheFidget(), and throwBallPlayer().