Podstawy grafiki komputerowej: GameObject Class Reference
GameObject Class Reference
Game object class.
#include <GameObject.hpp>
Public Member Functions
virtual ~GameObject ()
Destructor.
virtual void setPosition (Point2d pos)
Object position setter.
virtual Point2d getPosition () const
Object position getter.
virtual void move (Point2d vector)
Translates object in space.
Private Attributes
Point2d m_position {}
Position of object on screen.
Detailed Description
Game object class.
Definition at line 9 of file GameObject.hpp.
Constructor & Destructor Documentation
~GameObject()
virtual GameObject::~GameObject () inline virtual
Destructor.
Definition at line 20 of file GameObject.hpp.
{};
Member Function Documentation
getPosition()
Point2d GameObject::getPosition () const virtual
Object position getter.
Definition at line 7 of file GameObject.cpp.
{ return m_position; }
References m_position.
move()
void GameObject::move (Point2d vector) virtual
Translates object in space.
Parameters
vector 2D vector added to current object position.
Reimplemented in AnimatedObject, Player, and Ball.
Definition at line 9 of file GameObject.cpp.
{
  m_position += vector;
  // LOGINFO << vector << '\t' << m_position << '\n';
}
References m_position.
Referenced by AnimatedObject::move(), Player::move(), and Ball::move().
setPosition()
void GameObject::setPosition (Point2d pos) virtual
Object position setter.
Parameters
pos Position to be set.
Reimplemented in AnimatedObject.
Definition at line 5 of file GameObject.cpp.
{ m_position = pos; }
References m_position.
Referenced by AnimatedObject::setPosition(), and Ball::setPositon().
Member Data Documentation
m_position
Point2d GameObject::m_position {} private
Position of object on screen.
Definition at line 14 of file GameObject.hpp.
{};
Referenced by getPosition(), move(), and setPosition().
The documentation for this class was generated from the following files:
GameObject.hpp
GameObject.cpp