Podstawy grafiki komputerowej: Player Class Reference
Player Class Reference
Player class.
#include <player.hpp>
Public Types
enum class MoveDirection {
north , east , south , west ,
count
}
Directions of movement.
Public Member Functions
virtual ~Player ()
Destructor.
virtual void setIsMoving (MoveDirection direction)
virtual void stopMoving (MoveDirection direction)
void stopMoving ()
Stops player from moving.
bool isMoving () const
Checks if player is moving.
bool isMoving (MoveDirection direction) const
Checks if player is moving in a specific direction.
void setMovementSpeed (float speed)
Player movement speed setter.
virtual float getMovementSpeed () const
Player movement speed getter.
bool isMovingDiagonaly () const
Checks if player is moving diagonally.
Point2d getMoveVectorOrigin () const
Returns a 2D vector containing information on which cardinal directions the player is moving.
Point2d getMoveVector () const
Returns the player's movement vector multiplied by speed.
virtual void update ()
Updates state of object.
virtual void setPosition (Point2d pos)
Object position setter.
virtual void animate ()
Animates object.
virtual Point2d getPosition () const
Object position getter.
Private Member Functions
void move (Point2d vec)
Moves player on screen.
Private Attributes
float m_movementSpeed {50}
Player movement speed.
std::array< bool, static_cast< ssize_t >(MoveDirection::count)> m_isMoving {}
Array with player's current movement direction.
Point2d m_position {}
Position of object on screen.
Detailed Description
Player class.
Definition at line 16 of file player.hpp.
Member Enumeration Documentation
MoveDirection
enum class Player::MoveDirection strong
Directions of movement.
Enumerator
north
east
south
west
count
Definition at line 21 of file player.hpp.
{ north, east, south, west, count };
Constructor & Destructor Documentation
~Player()
Player::~Player () virtual
Destructor.
Definition at line 9 of file player.cpp.
{};
Member Function Documentation
animate()
void AnimatedObject::animate () virtual inherited
Animates object.
Reimplemented in Bush, AnimatedSpriteSheet, FidgetSpinner, and GamePlayer.
Definition at line 5 of file animatedObject.cpp.
{
  LOGWARN << "Not overloaded " << this << '\n';
};
References LOGWARN.
Referenced by Engine::animateObjects().
getMovementSpeed()
float Player::getMovementSpeed () const virtual
Player movement speed getter.
Definition at line 32 of file player.cpp.
{ return m_movementSpeed; };
References m_movementSpeed.
getMoveVector()
Point2d Player::getMoveVector () const
Returns the player's movement vector multiplied by speed.
Definition at line 40 of file player.cpp.
{
  return getMoveVectorOrigin() * m_movementSpeed *
         Engine::getInstance().getLastFrameDuration().asSeconds();
}
References Engine::getInstance(), Engine::getLastFrameDuration(), getMoveVectorOrigin(), and m_movementSpeed.
Referenced by move(), and update().
getMoveVectorOrigin()
Point2d Player::getMoveVectorOrigin () const
Returns a 2D vector containing information on which cardinal directions the player is moving.
Definition at line 17 of file player.cpp.
{
  Point2d vec{};
  if (m_isMoving[static_cast<int>(MoveDirection::north)])
    vec += {0, -1};
  if (m_isMoving[static_cast<int>(MoveDirection::east)])
    vec += {1, 0};
  if (m_isMoving[static_cast<int>(MoveDirection::south)])
    vec += {0, 1};
  if (m_isMoving[static_cast<int>(MoveDirection::west)])
    vec += {-1, 0};
  return vec;
}
References east, m_isMoving, north, south, and west.
Referenced by getMoveVector(), isMoving(), isMovingDiagonaly(), and throwBallPlayer().
getPosition()
Point2d GameObject::getPosition () const virtual inherited
Object position getter.
Definition at line 7 of file GameObject.cpp.
{ return m_position; }
References GameObject::m_position.
isMoving() [1/2]
bool Player::isMoving () const
Checks if player is moving.
Definition at line 53 of file player.cpp.
{
  bool moving{};
  return getMoveVectorOrigin() != Point2d{0, 0};
}
References getMoveVectorOrigin().
Referenced by GamePlayer::update().
isMoving() [2/2]
bool Player::isMoving (MoveDirection direction) const
Checks if player is moving in a specific direction.
Parameters
direction Direction checked.
Definition at line 58 of file player.cpp.
{
  return m_isMoving[static_cast<ssize_t>(direction)];
}
References m_isMoving.
isMovingDiagonaly()
bool Player::isMovingDiagonaly () const
Checks if player is moving diagonally.
Definition at line 34 of file player.cpp.
{
  Point2d vec{getMoveVectorOrigin()};
  auto absMoveDist{std::abs(vec.getX()) + std::abs(vec.getY())};
  return absMoveDist > 1;
}
References getMoveVectorOrigin().
Referenced by GamePlayer::update().
move()
void Player::move (Point2d vec) private virtual
Moves player on screen.
Parameters
vec Vector by which player is moved.
Reimplemented from AnimatedObject.
Definition at line 11 of file player.cpp.
{
  GameObject::move(vec);
  sf::Sprite::move(getMoveVector().toVector2f());
  // LOGINFO << GameObject::getPosition() << '\n';
};
References getMoveVector(), and GameObject::move().
Referenced by update().
setIsMoving()
void Player::setIsMoving (MoveDirection direction) virtual
Parameters
direction
Definition at line 45 of file player.cpp.
{
  m_isMoving[static_cast<ssize_t>(direction)] = true;
};
References m_isMoving.
Referenced by keyPressedEventHandler().
setMovementSpeed()
void Player::setMovementSpeed (float speed)
Player movement speed setter.
Definition at line 31 of file player.cpp.
{ m_movementSpeed = speed; }
References m_movementSpeed.
Referenced by initialziePlayer().
setPosition()
void AnimatedObject::setPosition (Point2d pos) virtual inherited
Object position setter.
Parameters
pos Position to be set.
Reimplemented from GameObject.
Definition at line 9 of file animatedObject.cpp.
{
  GameObject::setPosition(pos);
  sf::Sprite::setPosition(pos.toVector2f());
};
References GameObject::setPosition(), and Point2d::toVector2f().
Referenced by initializeFidgetSpinner(), and main().
stopMoving() [1/2]
void Player::stopMoving ()
Stops player from moving.
Definition at line 62 of file player.cpp.
{
  for (auto &it : m_isMoving) {
    it = false;
  }
}
References m_isMoving.
stopMoving() [2/2]
void Player::stopMoving (MoveDirection direction) virtual
Parameters
direction
Definition at line 49 of file player.cpp.
{
  m_isMoving[static_cast<ssize_t>(direction)] = false;
}
References m_isMoving.
Referenced by keyReleasedEventHandler().
update()
void Player::update () virtual
Updates state of object.
Implements UpdateableObject.
Reimplemented in GamePlayer.
Definition at line 68 of file player.cpp.
                    {
  Point2d vec = getMoveVector();
  move(vec);
};
References getMoveVector(), and move().
Referenced by GamePlayer::update().
Member Data Documentation
m_isMoving
std::array<bool, static_cast<ssize_t>(MoveDirection::count)> Player::m_isMoving {} private
Array with player's current movement direction.
Definition at line 31 of file player.hpp.
{};
Referenced by getMoveVectorOrigin(), isMoving(), setIsMoving(), stopMoving(), and stopMoving().
m_movementSpeed
float Player::m_movementSpeed {50} private
Player movement speed.
Definition at line 27 of file player.hpp.
{50};
Referenced by getMovementSpeed(), getMoveVector(), and setMovementSpeed().
m_position
Point2d GameObject::m_position {} private inherited
Position of object on screen.
Definition at line 14 of file GameObject.hpp.
{};
Referenced by GameObject::getPosition(), GameObject::move(), and GameObject::setPosition().
The documentation for this class was generated from the following files:
player.hpp
player.cpp