Podstawy grafiki komputerowej: AnimatedObject Class Reference
AnimatedObject Class Reference
Animated object class.
#include <animatedObject.hpp>
Public Member Functions
virtual ~AnimatedObject ()
Destructor.
virtual void setPosition (Point2d pos)
Object position setter.
virtual void animate ()
Animates object.
virtual void move (Point2d vec)
Translates object in space.
virtual Point2d getPosition () const
Object position getter.
Private Attributes
Point2d m_position {}
Position of object on screen.
Detailed Description
Animated object class.
Definition at line 13 of file animatedObject.hpp.
Constructor & Destructor Documentation
~AnimatedObject()
virtual AnimatedObject::~AnimatedObject () inline virtual
Destructor.
Definition at line 21 of file animatedObject.hpp.
{};
Member Function Documentation
animate()
void AnimatedObject::animate () virtual
Animates object.
Reimplemented in Bush, AnimatedSpriteSheet, FidgetSpinner, and GamePlayer.
Definition at line 5 of file animatedObject.cpp.
{
  LOGWARN << "Not overloaded " << this << '\n';
};
References LOGWARN.
Referenced by Engine::animateObjects().
getPosition()
Point2d GameObject::getPosition () const virtual inherited
Object position getter.
Definition at line 7 of file GameObject.cpp.
{ return m_position; }
References GameObject::m_position.
move()
void AnimatedObject::move (Point2d vector) virtual
Translates object in space.
Parameters
vector 2D vector added to current object position.
Reimplemented from GameObject.
Reimplemented in Player.
Definition at line 14 of file animatedObject.cpp.
{
  GameObject::move(vec);
  sf::Sprite::move(vec.toVector2f());
  // LOGINFO << GameObject::getPosition() << '\n';
};
References GameObject::move(), and Point2d::toVector2f().
setPosition()
void AnimatedObject::setPosition (Point2d pos) virtual
Object position setter.
Parameters
pos Position to be set.
Reimplemented from GameObject.
Definition at line 9 of file animatedObject.cpp.
{
  GameObject::setPosition(pos);
  sf::Sprite::setPosition(pos.toVector2f());
};
References GameObject::setPosition(), and Point2d::toVector2f().
Referenced by initializeFidgetSpinner(), and main().
Member Data Documentation
m_position
Point2d GameObject::m_position {} private inherited
Position of object on screen.
Definition at line 14 of file GameObject.hpp.
{};
Referenced by GameObject::getPosition(), GameObject::move(), and GameObject::setPosition().
The documentation for this class was generated from the following files:
animatedObject.hpp
animatedObject.cpp