Podstawy grafiki komputerowej: Engine Class Reference
Engine Class Reference
The engine class.
#include <engine.hpp>
Public Types
using Time = sf::Time
using Clock = sf::Clock
using RenderWindow = sf::RenderWindow
using Event = sf::Event
using Drawable = sf::Drawable
using Shape = sf::Shape
using eventHandler_t = std::function< void(const Event &)>
using drawableCollection_t = std::set< Drawable * >
using animatedObjecsCollection_t = std::set< AnimatedObject * >
Public Member Functions
Engine ()
Constructor.
~Engine ()
Destructor.
Engine & setMaxFps (int fps)
Set Max FPS.
Engine & setWindowTitle (std::string_view title)
Set window title.
Engine & setResolution (Point2d resolution)
Set resolution.
Engine & setResolution (Point2d::cordinate_t x, Point2d::cordinate_t y)
Set resolution.
Engine & setLoopFunction (std::function< void()> function)
Set function that is invoked in the main loop.
Engine & setEventHandler (Event::EventType eventType, eventHandler_t handler)
Set custom event handler.
Point2d getResolution () const
Resolution getter.
Engine & buildWindow ()
Builds the window.
void handleEvents ()
Handles events.
void clear ()
Clears window to a single color.
void render ()
Renders objects.
void display ()
Displays rendered objects.
void loop ()
The main loop.
RenderWindow & getWindow ()
Window getter.
void add (Drawable *drawable)
Adds drawable to Collection.
void add (AnimatedObject *animatedObject)
Adds animated object to Collection.
void remove (Drawable *)
Time getLastFrameDuration () const
Last frame duration getter.
Static Public Member Functions
static Engine & getInstance ()
Instance getter.
Private Member Functions
void drawDrawables ()
Draws objects.
void animateObjects ()
Draws animated objects.
Private Attributes
std::function< void()> m_loopFunction {[]() {}}
custom function fired in the main loop.
RenderWindow m_window {}
Window to draw stuff on.
Point2d m_resoltuon {1000, 800}
Resolution of the window.
std::string m_windowTitle {"dev"}
Window title.
int m_maxFPS {60}
Max FPS.
std::array< eventHandler_t, Event::Count > m_eventHandlers
Custom functions handling events.
drawableCollection_t m_drawablesCollection {}
Stuff that is drawn in the window each frame.
animatedObjecsCollection_t m_animatedObjectsCollection {}
Clock m_clock {}
Clock for computing ticks.
Time m_lastFrameDuration {}
Duration of the last frame.
Static Private Attributes
static Engine * s_instancePtr {nullptr}
Pointer to the instance.
Detailed Description
The engine class.
Definition at line 18 of file engine.hpp.
Member Typedef Documentation
animatedObjecsCollection_t
using Engine::animatedObjecsCollection_t = std::set<AnimatedObject *>
Definition at line 29 of file engine.hpp.
Clock
using Engine::Clock = sf::Clock
Definition at line 21 of file engine.hpp.
Drawable
using Engine::Drawable = sf::Drawable
Definition at line 24 of file engine.hpp.
drawableCollection_t
using Engine::drawableCollection_t = std::set<Drawable *>
Definition at line 28 of file engine.hpp.
Event
using Engine::Event = sf::Event
Definition at line 23 of file engine.hpp.
eventHandler_t
using Engine::eventHandler_t = std::function<void(const Event &)>
Definition at line 27 of file engine.hpp.
RenderWindow
using Engine::RenderWindow = sf::RenderWindow
Definition at line 22 of file engine.hpp.
Shape
using Engine::Shape = sf::Shape
Definition at line 25 of file engine.hpp.
Time
using Engine::Time = sf::Time
Definition at line 20 of file engine.hpp.
Constructor & Destructor Documentation
Engine()
Engine::Engine ()
Constructor.
Fills custom event handlers with placeholder functions.
Definition at line 14 of file engine.cpp.
               {
  LOGINFON;
  m_eventHandlers.fill([](const sf::Event &event) {});
}
References LOGINFON, and m_eventHandlers.
Referenced by getInstance().
~Engine()
Engine::~Engine ()
Destructor.
Definition at line 20 of file engine.cpp.
                {
  LOGINFON;
  for (sf::Drawable *it : m_drawablesCollection) {
    delete it;
  }
  for (AnimatedObject *it : m_animatedObjectsCollection) {
    delete it;
  }
}
References LOGINFON, m_animatedObjectsCollection, and m_drawablesCollection.
Member Function Documentation
add() [1/2]
void Engine::add (AnimatedObject * animatedObject)
Adds animated object to Collection.
Parameters
animatedObject animated object.
Definition at line 127 of file engine.cpp.
{
  LOGINFO << animatedObject << '\n';
  m_animatedObjectsCollection.insert(animatedObject);
}
References LOGINFO, and m_animatedObjectsCollection.
add() [2/2]
void Engine::add (Drawable * drawable)
Adds drawable to Collection.
Parameters
drawable Drawable shape.
Definition at line 122 of file engine.cpp.
{
  LOGINFO << drawable << '\n';
  m_drawablesCollection.insert(drawable);
}
References LOGINFO, and m_drawablesCollection.
Referenced by addSomeRenderables(), initializeBush(), initializeFidgetSpinner(), initialziePlayer(), main(), and throwBall().
animateObjects()
void Engine::animateObjects () private
Draws animated objects.
Definition at line 145 of file engine.cpp.
{
  for (auto it : m_animatedObjectsCollection) {
    it->animate();
    getWindow().draw(*it);
  }
}
References AnimatedObject::animate(), getWindow(), and m_animatedObjectsCollection.
Referenced by render().
buildWindow()
Engine & Engine::buildWindow ()
Builds the window.
Definition at line 53 of file engine.cpp.
{
  LOGINFON;
  m_window.create({static_cast<unsigned int>(m_resoltuon.getX()),
                   static_cast<unsigned int>(m_resoltuon.getY())},
                  m_windowTitle);
  m_window.setFramerateLimit(m_maxFPS);
  return getInstance();
}
References getInstance(), Point2d::getX(), Point2d::getY(), LOGINFON, m_maxFPS, m_resoltuon, m_window, and m_windowTitle.
Referenced by main().
clear()
void Engine::clear ()
Clears window to a single color.
Definition at line 94 of file engine.cpp.
{ m_window.clear(); }
References m_window.
Referenced by loop().
display()
void Engine::display ()
Displays rendered objects.
Definition at line 101 of file engine.cpp.
{ m_window.display(); }
References m_window.
Referenced by loop().
drawDrawables()
void Engine::drawDrawables () private
Draws objects.
Definition at line 140 of file engine.cpp.
{
  for (auto &it : m_drawablesCollection)
    getWindow().draw(*it);
}
References getWindow(), and m_drawablesCollection.
Referenced by render().
getInstance()
Engine & Engine::getInstance () static
Instance getter.
Definition at line 30 of file engine.cpp.
{
  if (s_instancePtr == nullptr)
    s_instancePtr = new Engine;
  return *s_instancePtr;
}
References Engine(), and s_instancePtr.
Referenced by addSomeRenderables(), Bush::animate(), AnimatedSpriteSheet::animate(), FidgetSpinner::animate(), GamePlayer::animate(), buildWindow(), customLoopFunction(), obstacle::LineSegment::draw(), Player::getMoveVector(), handleBalls(), main(), setMaxFps(), setResolution(), setUpCustomEvents(), setWindowTitle(), and Ball::update().
getLastFrameDuration()
Engine::Time Engine::getLastFrameDuration () const
Last frame duration getter.
Definition at line 136 of file engine.cpp.
{
  return m_lastFrameDuration;
}
References m_lastFrameDuration.
Referenced by Bush::animate(), AnimatedSpriteSheet::animate(), FidgetSpinner::animate(), GamePlayer::animate(), customLoopFunction(), Player::getMoveVector(), and Ball::update().
getResolution()
Point2d Engine::getResolution () const
Resolution getter.
Definition at line 68 of file engine.cpp.
{ return m_resoltuon; }
References m_resoltuon.
getWindow()
Engine::RenderWindow & Engine::getWindow ()
Window getter.
Definition at line 120 of file engine.cpp.
{ return m_window; }
References m_window.
Referenced by animateObjects(), obstacle::LineSegment::draw(), drawDrawables(), and keyPressedEventHandler().
handleEvents()
void Engine::handleEvents ()
Handles events.
Definition at line 70 of file engine.cpp.
{
  sf::Event event;
  while (m_window.pollEvent(event)) {
    if (event.type == sf::Event::Closed)
      m_window.close();
    if (event.type == sf::Event::Resized) {
      // Update engine info
      m_resoltuon.setX(event.size.width);
      m_resoltuon.setY(event.size.height);
      // make new view
      sf::FloatRect view{0, 0, static_cast<float>(m_resoltuon.getX()),
                         static_cast<float>(m_resoltuon.getY())};
      m_window.setView(sf::View{view});
      LOGINFO << "Resized\t" << event.size.width << '\t' << event.size.height
              << '\n';
    }
    // Fire custom event handler.
    m_eventHandlers[event.type](event);
  }
}
References Point2d::getX(), Point2d::getY(), LOGINFO, m_eventHandlers, m_resoltuon, m_window, Point2d::setX(), and Point2d::setY().
Referenced by loop().
loop()
void Engine::loop ()
The main loop.
Definition at line 103 of file engine.cpp.
                  {
  LOGINFON;
  while (m_window.isOpen()) {
    clear();
    handleEvents();
    // restart clock
    m_lastFrameDuration = m_clock.restart();
    m_loopFunction();
    render();
    display();
  }
}
References clear(), display(), handleEvents(), LOGINFON, m_clock, m_lastFrameDuration, m_loopFunction, m_window, and render().
Referenced by main().
remove()
void Engine::remove (Engine::Drawable * drawable)
Definition at line 132 of file engine.cpp.
{
  m_drawablesCollection.erase(drawable);
}
References m_drawablesCollection.
Referenced by handleBalls().
render()
void Engine::render ()
Renders objects.
Definition at line 96 of file engine.cpp.
                    {
  animateObjects();
  drawDrawables();
}
References animateObjects(), and drawDrawables().
Referenced by loop().
setEventHandler()
Engine & Engine::setEventHandler (Event::EventType eventType, eventHandler_t handler)
Set custom event handler.
Parameters
eventType Type of event that handler receives.
handler Function handling the event.
Definition at line 62 of file engine.cpp.
{
  m_eventHandlers[eventType] = handler;
  return *this;
}
References m_eventHandlers.
Referenced by main(), and setUpCustomEvents().
setLoopFunction()
Engine & Engine::setLoopFunction (std::function< void()> function) inline
Set function that is invoked in the main loop.
Parameters
function Function that will be called in loop.
Definition at line 114 of file engine.hpp.
{
    m_loopFunction = function;
    return *this;
  };
References m_loopFunction.
Referenced by main().
setMaxFps()
Engine & Engine::setMaxFps (int fps)
Set Max FPS.
Parameters
fps max FPS.
Definition at line 36 of file engine.cpp.
{
  LOGINFON;
  m_maxFPS = fps;
  m_window.setFramerateLimit(fps);
  return getInstance();
}
References getInstance(), LOGINFON, m_maxFPS, and m_window.
Referenced by main().
setResolution() [1/2]
Engine & Engine::setResolution (Point2d resolution)
Set resolution.
Parameters
resolution Resolution to be set.
Definition at line 48 of file engine.cpp.
{
  m_resoltuon = resolution;
  return getInstance();
}
References getInstance(), and m_resoltuon.
Referenced by main(), and setResolution().
setResolution() [2/2]
Engine & Engine::setResolution (Point2d::cordinate_t x, Point2d::cordinate_t y) inline
Set resolution.
Definition at line 106 of file engine.hpp.
{
    setResolution({x, y});
    return *this;
  };
References setResolution().
setWindowTitle()
Engine & Engine::setWindowTitle (std::string_view title)
Set window title.
Parameters
title Title.
Definition at line 43 of file engine.cpp.
{
  m_windowTitle = title;
  return getInstance();
}
References getInstance(), and m_windowTitle.
Referenced by main().
Member Data Documentation
m_animatedObjectsCollection
animatedObjecsCollection_t Engine::m_animatedObjectsCollection {} private
Definition at line 64 of file engine.hpp.
{};
Referenced by add(), animateObjects(), and ~Engine().
m_clock
Clock Engine::m_clock {} private
Clock for computing ticks.
Definition at line 68 of file engine.hpp.
{};
Referenced by loop().
m_drawablesCollection
drawableCollection_t Engine::m_drawablesCollection {} private
Stuff that is drawn in the window each frame.
Definition at line 62 of file engine.hpp.
{};
Referenced by add(), drawDrawables(), remove(), and ~Engine().
m_eventHandlers
std::array<eventHandler_t, Event::Count> Engine::m_eventHandlers private
Custom functions handling events.
Definition at line 57 of file engine.hpp.
Referenced by Engine(), handleEvents(), and setEventHandler().
m_lastFrameDuration
Time Engine::m_lastFrameDuration {} private
Duration of the last frame.
Definition at line 73 of file engine.hpp.
{};
Referenced by getLastFrameDuration(), and loop().
m_loopFunction
std::function<void()> Engine::m_loopFunction {[]() {}} private
custom function fired in the main loop.
Definition at line 38 of file engine.hpp.
{[]() {}};
Referenced by loop(), and setLoopFunction().
m_maxFPS
int Engine::m_maxFPS {60} private
Max FPS.
Definition at line 52 of file engine.hpp.
{60};
Referenced by buildWindow(), and setMaxFps().
m_resoltuon
Point2d Engine::m_resoltuon {1000, 800} private
Resolution of the window.
Definition at line 45 of file engine.hpp.
{1000, 800};
Referenced by buildWindow(), getResolution(), handleEvents(), and setResolution().
m_window
RenderWindow Engine::m_window {} private
Window to draw stuff on.
Definition at line 42 of file engine.hpp.
{};
Referenced by buildWindow(), clear(), display(), getWindow(), handleEvents(), loop(), and setMaxFps().
m_windowTitle
std::string Engine::m_windowTitle {"dev"} private
Window title.
Definition at line 48 of file engine.hpp.
{"dev"};
Referenced by buildWindow(), and setWindowTitle().
s_instancePtr
Engine * Engine::s_instancePtr {nullptr} static private
Pointer to the instance.
Definition at line 12 of file engine.hpp.
Referenced by getInstance().
The documentation for this class was generated from the following files:
engine.hpp
engine.cpp