Podstawy grafiki komputerowej: AnimatedSpriteSheet::AnimationFrameData Struct Reference
AnimatedSpriteSheet::AnimationFrameData Struct Reference
#include <animatedSpriteSheet.hpp>
Public Member Functions
sf::IntRect toIntRect () const
Public Attributes
float m_duration
Point2d m_size
Point2d m_position
Friends
std::istream & operator>> (std::istream &is, AnimationFrameData &afd)
Detailed Description
Definition at line 11 of file animatedSpriteSheet.hpp.
Member Function Documentation
toIntRect()
sf::IntRect AnimatedSpriteSheet::AnimationFrameData::toIntRect () const
Definition at line 20 of file animatedSpriteSheet.cpp.
{
  LOGTRACEN;
  return {static_cast<int>(m_position.getX()),
          static_cast<int>(m_position.getY()), static_cast<int>(m_size.getX()),
          static_cast<int>(m_size.getY())};
}
References Point2d::getX(), Point2d::getY(), LOGTRACEN, m_position, and m_size.
Referenced by AnimatedSpriteSheet::setFrame().
Friends And Related Symbol Documentation
operator>>
std::istream & operator>> (std::istream & is, AnimatedSpriteSheet::AnimationFrameData & afd) friend
Definition at line 11 of file animatedSpriteSheet.cpp.
{
  LOGTRACEN;
  is >> afd.m_position;
  is >> afd.m_size;
  is >> afd.m_duration;
  return is;
}
Member Data Documentation
m_duration
float AnimatedSpriteSheet::AnimationFrameData::m_duration
Definition at line 13 of file animatedSpriteSheet.hpp.
Referenced by AnimatedSpriteSheet::getCurrentAnimationFrameDuration().
m_position
Point2d AnimatedSpriteSheet::AnimationFrameData::m_position
Definition at line 17 of file animatedSpriteSheet.hpp.
Referenced by FidgetSpinner::getCenterPoint(), and toIntRect().
m_size
Point2d AnimatedSpriteSheet::AnimationFrameData::m_size
Definition at line 15 of file animatedSpriteSheet.hpp.
Referenced by FidgetSpinner::getCenterPoint(), and toIntRect().
The documentation for this struct was generated from the following files:
animatedSpriteSheet.hpp
animatedSpriteSheet.cpp