Podstawy grafiki komputerowej: Bush Class Reference
Bush Class Reference
#include <bush.hpp>
Public Member Functions
Bush ()
~Bush ()
virtual void animate ()
Animates object.
virtual void setPosition (Point2d pos)
Object position setter.
virtual void move (Point2d vec)
Translates object in space.
virtual Point2d getPosition () const
Object position getter.
Private Member Functions
void nextSprite ()
sf::IntRect getCurrentSpriteRectangle (int frameNumber)
Private Attributes
int m_aninmationFrameIndicator {}
float m_animationFrameDuration {1}
float m_animationTimer {}
Point2d m_position {}
Position of object on screen.
Static Private Attributes
static constexpr std::string_view s_spriteSheetPath {"resource/bush/bush.png"}
Detailed Description
Definition at line 8 of file bush.hpp.
Constructor & Destructor Documentation
Bush()
Bush::Bush ()
Definition at line 10 of file bush.cpp.
           {
  LOGINFON;
  loadFromFile(std::string(s_spriteSheetPath), sf::IntRect{0, 0, 300, 150});
  setTexture(*this);
  setTextureRect(getCurrentSpriteRectangle(0));
}
References getCurrentSpriteRectangle(), LOGINFON, and s_spriteSheetPath.
~Bush()
Bush::~Bush ()
Definition at line 8 of file bush.cpp.
{};
Member Function Documentation
animate()
void Bush::animate () virtual
Animates object.
Reimplemented from AnimatedObject.
Definition at line 17 of file bush.cpp.
                   {
  m_animationTimer += Engine::getInstance().getLastFrameDuration().asSeconds();
  if (m_animationTimer < m_animationFrameDuration)
    return;
  m_animationTimer = 0;
  nextSprite();
}
References Engine::getInstance(), Engine::getLastFrameDuration(), m_animationFrameDuration, m_animationTimer, and nextSprite().
getCurrentSpriteRectangle()
sf::IntRect Bush::getCurrentSpriteRectangle (int frameNumber) private
Definition at line 32 of file bush.cpp.
{
  return sf::IntRect{frameNumber * 150, 0, 150, 150};
}
Referenced by Bush(), and nextSprite().
getPosition()
Point2d GameObject::getPosition () const virtual inherited
Object position getter.
Definition at line 7 of file GameObject.cpp.
{ return m_position; }
References GameObject::m_position.
move()
void AnimatedObject::move (Point2d vector) virtual inherited
Translates object in space.
Parameters
vector 2D vector added to current object position.
Reimplemented from GameObject.
Reimplemented in Player.
Definition at line 14 of file animatedObject.cpp.
{
  GameObject::move(vec);
  sf::Sprite::move(vec.toVector2f());
  // LOGINFO << GameObject::getPosition() << '\n';
};
References GameObject::move(), and Point2d::toVector2f().
nextSprite()
void Bush::nextSprite () private
Definition at line 26 of file bush.cpp.
                      {
  this->setTextureRect(getCurrentSpriteRectangle(m_aninmationFrameIndicator));
  ++m_aninmationFrameIndicator;
  m_aninmationFrameIndicator %= 2;
}
References getCurrentSpriteRectangle(), and m_aninmationFrameIndicator.
Referenced by animate().
setPosition()
void AnimatedObject::setPosition (Point2d pos) virtual inherited
Object position setter.
Parameters
pos Position to be set.
Reimplemented from GameObject.
Definition at line 9 of file animatedObject.cpp.
{
  GameObject::setPosition(pos);
  sf::Sprite::setPosition(pos.toVector2f());
};
References GameObject::setPosition(), and Point2d::toVector2f().
Referenced by initializeFidgetSpinner(), and main().
Member Data Documentation
m_animationFrameDuration
float Bush::m_animationFrameDuration {1} private
Definition at line 11 of file bush.hpp.
{1};
Referenced by animate().
m_animationTimer
float Bush::m_animationTimer {} private
Definition at line 12 of file bush.hpp.
{};
Referenced by animate().
m_aninmationFrameIndicator
int Bush::m_aninmationFrameIndicator {} private
Definition at line 10 of file bush.hpp.
{};
Referenced by nextSprite().
m_position
Point2d GameObject::m_position {} private inherited
Position of object on screen.
Definition at line 14 of file GameObject.hpp.
{};
Referenced by GameObject::getPosition(), GameObject::move(), and GameObject::setPosition().
s_spriteSheetPath
constexpr std::string_view Bush::s_spriteSheetPath {"resource/bush/bush.png"} static constexpr private
Definition at line 9 of file bush.hpp.
{"resource/bush/bush.png"};
Referenced by Bush().
The documentation for this class was generated from the following files:
bush.hpp
bush.cpp