Podstawy grafiki komputerowej: obstacle::LineSegment Class Reference
obstacle::LineSegment Class Reference
#include <lineSegment.hpp>
Public Member Functions
LineSegment (Point2d start, Point2d end, sf::Color color={})
void draw () const
Point2d getStart () const
Point2d getEnd () const
void setStart (Point2d val)
void setEnd (Point2d val)
void setColor (sf::Color color)
Private Attributes
sf::Vertex m_points [2] = {}
sf::Color m_color
Detailed Description
Definition at line 14 of file lineSegment.hpp.
Constructor & Destructor Documentation
LineSegment()
obstacle::LineSegment::LineSegment (Point2d start, Point2d end, sf::Color color = {})
Definition at line 15 of file lineSegment.cpp.
    : m_points{{start.toVector2f(), color}, {end.toVector2f(), color}},
      m_color{color} {};
References Point2d::toVector2f().
Member Function Documentation
draw()
void obstacle::LineSegment::draw () const
Definition at line 19 of file lineSegment.cpp.
{
  Engine::getInstance().getWindow().draw(m_points, 2, sf::Lines);
}
References Engine::getInstance(), and Engine::getWindow().
getEnd()
Point2d obstacle::LineSegment::getEnd () const
Definition at line 24 of file lineSegment.cpp.
{ return Point2d{m_points[1].position}; }
getStart()
Point2d obstacle::LineSegment::getStart () const
Definition at line 23 of file lineSegment.cpp.
{ return Point2d{m_points[0].position}; }
setColor()
void obstacle::LineSegment::setColor (sf::Color color) inline
Definition at line 29 of file lineSegment.hpp.
{ m_color = color; };
References m_color.
setEnd()
void obstacle::LineSegment::setEnd (Point2d val)
Definition at line 29 of file lineSegment.cpp.
{
  m_points[1].position = val.toVector2f();
}
References Point2d::toVector2f().
setStart()
void obstacle::LineSegment::setStart (Point2d val)
Definition at line 26 of file lineSegment.cpp.
{
  m_points[0].position = val.toVector2f();
}
References Point2d::toVector2f().
Member Data Documentation
m_color
sf::Color obstacle::LineSegment::m_color private
Definition at line 16 of file lineSegment.hpp.
Referenced by setColor().
m_points
sf::Vertex obstacle::LineSegment::m_points[2] = {} private
Definition at line 15 of file lineSegment.hpp.
{};
The documentation for this class was generated from the following files:
lineSegment.hpp
lineSegment.cpp